sudo: required
services:
  - docker

before_install:
  - docker build -t vincentyuuu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test yarn test

after_success:
  - docker build -t vincentyuuu/multi-client ./client
  - docker build -t vincentyuuu/multi-nginx ./nginx
  - docker build -t vincentyuuu/multi-server ./server
  - docker build -t vincentyuuu/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push vincentyuuu/multi-client
  - docker push vincentyuuu/multi-nginx
  - docker push vincentyuuu/multi-server
  - docker push vincentyuuu/multi-worker
